#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     irF,            sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     lightF,         sensorLightActive)
#pragma config(Sensor, S4,     irR,            sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     fr,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     fl,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     bl,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     br,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftA,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftB,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     holder,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     flagspinner,   tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
/*#include "hitechnic-sensormux.h"
#include "lego-touch.h"
#include "lego-light.h"
*/
//#define touchBack              msensor_S4_1
//#define lightL             msensor_S4_2
//#define lightR          msensor_S4_3

const int ON_TAPE = 480;
//const int OFF_TAPE = 450;


bool tapeify();

void initializeRobot(){
	bFloatDuringInactiveMotorPWM = false;
	return;
}

void takeDump(){
	motor[holder] = -100;
	wait1Msec(200);
	motor[holder] = 0;
	wait1Msec(600);
	motor[holder] = 100;
	wait1Msec(300);
	motor[holder] = 0;
	wait1Msec(300);
	motor[holder] = -100;
	wait1Msec(300) ;
}


	bool probablyOffTape = false;

void liftUpAndDownAndTakeDumpAndForward(){
	motor[fr] = 25;
	motor[fl] = 25;
	motor[br] = 25;
	motor[bl] = 25;

	wait10Msec(60);

	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;

	motor[liftA] = 100;
	motor[liftB] = 100;
	wait10Msec(450);
	motor[liftA] = 0;
	motor[liftB] = 0;

	takeDump();

	motor[liftA] = -100;
	motor[liftB] = -100;
	wait10Msec(400);
	motor[liftA] = 0;
	motor[liftB] = 0;

	motor[fr] = -25;
	motor[fl] = -25;
	motor[br] = -25;
	motor[bl] = -25;

	wait10Msec(60);
			motor[fr] = -0;
		motor[fl] = 0;
		motor[br] = -0;
		motor[bl] = 0;
	wait10Msec(30)
	while(SensorValue[irR] != 5 && !SensorValue[irF] != 9){
			motor[fr] = 17;
		motor[fl] = -0;
		motor[br] = 17;
		motor[bl] = -17;

	}
		motor[fr] = 0;
		motor[fl] = -0;
		motor[br] = 0;
		motor[bl] = -0;
	while(SensorRaw[lightF] >= ON_TAPE){
		motor[fr] = 34;
		motor[fl] = 17;
		motor[br] = 34;
		motor[bl] = 17;

	}
		motor[fr] = 0;
		motor[fl] = -0;
		motor[br] = 0;
		motor[bl] = 0;
		}
void irify(){
	PlaySound(soundBeepBeep);
	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;
	wait1Msec(1000);


	ClearTimer(T1);
	while(SensorValue[irF] != 4){
		motor[fr] = -17;
		motor[fl] = 17;
		motor[br] = -17;
		motor[bl] = 17;
	}

	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;

	liftUpAndDownAndTakeDumpAndForward();


}
bool tapeify(){
	//while(false){
	//drive forward until left light loses tape and scan for IR beacon


	if(SensorRaw[lightF]  >= ON_TAPE){
		motor[fr] = 10;
		motor[fl] = 20;
		motor[br] = 10;
		motor[bl] = 20;
	}
	else{
		ClearTimer(T1);
		int timeCorrection = 0;
		while(SensorRaw[lightF]  <= ON_TAPE){
			motor[fr] = 20;
			motor[fl] = 0;
			motor[br] = 20;
			motor[bl] = 0;
			if(time1[T1] > 300){
				probablyOffTape = true;
				break;
			}
		}
		timeCorrection = time1[T1];
		ClearTimer(T1);
		while(time1[T1] < timeCorrection){
			motor[fr] = 0;
			motor[fl] = 20;
			motor[br] = 0;
			motor[bl] = 20;
		}

		return !probablyOffTape;
	}
}



task updateDisplay(){
	while(true){
		nxtDisplayTextLine(1, "%d" ,SensorRaw[lightF]);
		nxtDisplayTextLine(2, "%d" ,SensorValue[irR]);
		nxtDisplayTextLine(3, "%d" ,SensorValue[irF]);
	}
}
task main()
{
	bool probablyOffTape = false;
	initializeRobot();


	motor[motorA] = -50;

	wait1Msec(700);

	StartTask(updateDisplay);
//waitForStart();
	while(SensorRaw[lightF]  <= ON_TAPE){
		motor[fr] = 10;
		motor[fl] = 15;
		motor[br] = 10;
		motor[bl] = 15;
	}

	PlaySound(soundBeepBeep);

	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;



	while(true){
		if(SensorValue[irR] == 5 && SensorValue[irF] == 9){
			irify();
			break;
		}
		else{
			probablyOffTape = tapeify();
		}
	}

	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;

	while(true){

	}

	//	PlaySound(soundBeepBeep);
}
