#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     frontLight,     sensorLightInactive)
#pragma config(Sensor, S3,     backLight,      sensorLightInactive)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     fr,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     fl,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     bl,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     br,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftA,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftB,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     holder,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     flagspinner,   tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "hitechnic-sensormux.h"
#include "hitechnic-irseeker-v2.h"
#include "lego-ultrasound.h"

#define sonicSensor              msensor_S4_1
#define frontRightIR              msensor_S4_2
#define frontLeftIR              msensor_S4_3
#define backRightIR              msensor_S4_4

const int ON_TAPE = 480;
//const int OFF_TAPE = 450;


bool tapeify();

task burp(){
	motor[liftA] = 100;
	motor[liftB] = 100;
	wait10Msec(450);
	motor[liftA] = 0;
	motor[liftB] = 0;
}

void initializeRobot(){
	bFloatDuringInactiveMotorPWM = false;
	return;
}

void liftUp(){
	motor[liftA] = 100;
	motor[liftB] = 100;
	wait10Msec(450);
	motor[liftA] = 0;
	motor[liftB] = 0;
}

bool tapeify(){

}



task updateDisplay(){
	while(true){
		nxtDisplayTextLine(1, "%d" ,SensorRaw[frontLight]);
		nxtDisplayTextLine(2, "%d" ,SensorRaw[backLight]);
	}
}

task main()
{
	initializeRobot();

	wait1Msec(700);

	StartTask(updateDisplay);
	//waitForStart();
	while(SensorRaw[lightF]  <= ON_TAPE){
		motor[fr] = 10;
		motor[fl] = 15;
		motor[br] = 10;
		motor[bl] = 15;
	}

	PlaySound(soundBeepBeep);

	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;

	StartTask(burp);


	while(true){
		if(SensorValue[irR] == 5 && SensorValue[irF] == 9){
			irify();
			break;
		}
		else{
			probablyOffTape = tapeify();
		}
	}

	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;

	while(true){

	}

	//	PlaySound(soundBeepBeep);
}
