#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     frontLight,     sensorLightActive)
#pragma config(Sensor, S3,     backLight,      sensorLightActive)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     fr,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     fl,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     bl,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     br,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftA,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftB,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     holder,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     flagspinner,   tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-sensormux.h"
#include "hitechnic-irseeker-v2.h"
#include "lego-ultrasound.h"

#define sonicSensor              msensor_S4_1
#define frontRightIR              msensor_S4_3
#define frontLeftIR              msensor_S4_2
#define backRightIR              msensor_S4_4

const int FRONT_ON_TAPE = 480;
const int BACK_ON_TAPE = 340;


bool tapeify();

task burp(){
	motor[liftA] = 100;
	motor[liftB] = 100;
	wait10Msec(450);
	motor[liftA] = 0;
	motor[liftB] = 0;
}

void initializeRobot(){
	bFloatDuringInactiveMotorPWM = false;
	return;
}

void liftUp(){
	motor[liftA] = 100;
	motor[liftB] = 100;
	wait10Msec(450);
	motor[liftA] = 0;
	motor[liftB] = 0;
}

void takeDump(){
	motor[holder] = -100;
	wait1Msec(200);
	motor[holder] = 0;
	wait1Msec(600);
	motor[holder] = 100;
	wait1Msec(300);
	motor[holder] = 0;
	wait1Msec(300);
	motor[holder] = -100;
	wait1Msec(300) ;
}

task floooop(){
	for(int i = 0; i < 20000; i++){
		PlayTone(i, 2);
	}
}

task fleeeep(){
	for(int i = 20000; i > 20; i--){
		PlayTone(i, 2);
	}
}


void liftUpAndDownAndTakeDumpAndForward(){
	motor[fr] = 25;
	motor[fl] = 25;
	motor[br] = 25;
	motor[bl] = 25;

	wait10Msec(6);

	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;

	motor[liftA] = 100;
	motor[liftB] = 100;
	wait1Msec(3100);
	motor[liftA] = 0;
	motor[liftB] = 0;

	takeDump();

	motor[liftA] = -100;
	motor[liftB] = -100;
	wait1Msec(2900);
	motor[liftA] = 0;
	motor[liftB] = 0;

	motor[fr] = -25;
	motor[fl] = -25;
	motor[br] = -25;
	motor[bl] = -25;

	wait10Msec(60);
	motor[fr] = -0;
	motor[fl] = 0;
	motor[br] = -0;
	motor[bl] = 0;
	wait10Msec(30);
	while(HTIRS2readACDir(backRightIR) != 5 && HTIRS2readACDir(frontRightIR) != 9){
		motor[fr] = 17;
		motor[fl] = -0;
		motor[br] = 17;
		motor[bl] = -17;

	}
	motor[fr] = 0;
	motor[fl] = -0;
	motor[br] = 0;
	motor[bl] = -0;
	while(SensorRaw[frontLight] >= FRONT_ON_TAPE){
		motor[fr] = 34;
		motor[fl] = 17;
		motor[br] = 34;
		motor[bl] = 17;

	}
	motor[fr] = 0;
	motor[fl] = -0;
	motor[br] = 0;
	motor[bl] = 0;
}
task updateDisplay(){
	while(true){
		nxtDisplayTextLine(1, "%d" ,SensorRaw[frontLight]);
		nxtDisplayTextLine(2, "%d" ,HTIRS2readACDir(backRightIR));
		nxtDisplayTextLine(3, "%d" ,HTIRS2readACDir(frontRightIR));
	}
}

bool tapeify(){
	//while(false){
	//drive forward until left light loses tape and scan for IR beacon

	bool probablyOffTape = false;


	if(SensorRaw[frontLight]  >= FRONT_ON_TAPE){
		motor[fr] = 10;
		motor[fl] = 15;
		motor[br] = 10;
		motor[bl] = 15;
	}
	else{
		ClearTimer(T1);
		int timeCorrection = 0;
		while(SensorRaw[frontLight]  <= FRONT_ON_TAPE){
			motor[fr] = 20;
			motor[fl] = 0;
			motor[br] = 20;
			motor[bl] = 0;
			if(time1[T1] > 300){
				probablyOffTape = true;
				break;
			}
		}
		timeCorrection = time1[T1];
		ClearTimer(T1);
		while(time1[T1] < timeCorrection){
			motor[fr] = 0;
			motor[fl] = 20;
			motor[br] = 0;
			motor[bl] = 20;
		}

		return probablyOffTape;
	}
}
void irify(){
	PlaySound(soundBeepBeep);
	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;
	wait1Msec(1000);

	while(HTIRS2readACDir(frontRightIR) > 1){
		motor[fr] = -17;
		motor[fl] = 17;
		motor[br] = -17;
		motor[bl] = 17;
	}

	StartTask(floooop);

	while(SensorRaw[frontLight]  <= FRONT_ON_TAPE){
		motor[fr] = 10;
		motor[fl] = 12;
		motor[br] = 10;
		motor[bl] = 12;
	}

	StartTask(fleeeep);



	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;

	liftUpAndDownAndTakeDumpAndForward();


}

task main()
{
	bool probablyOffTape = false;
	initializeRobot();


	motor[motorA] = -50;

	wait1Msec(700);

	StartTask(updateDisplay);
	//waitForStart();
	while(SensorRaw[frontLight]  <= FRONT_ON_TAPE){
		motor[fr] = 10;
		motor[fl] = 15;
		motor[br] = 10;
		motor[bl] = 15;
	}

	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;



	while(true){
		if(HTIRS2readACDir(frontRightIR) == 5 && HTIRS2readACDir(backRightIR) == 9){
			irify();
			break;
		}
		else{
			probablyOffTape = tapeify();
		}
	}

	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;

	while(true){

	}

	//	PlaySound(soundBeepBeep);
}
