#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     fl,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     bl,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     br,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     fr,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_1,     shooterA,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     shooterB,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_2,     derpmotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    holdleft,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    holdright,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void initializeRobot()
{
	return;
}

void spin(bool clockwise){
	//spin (clockwise?)
	if(clockwise){
		motor[fr] = -100*speed;
		motor[fl] = 100*speed;
		motor[bl] = 100*speed ;
		motor[br] = -100*speed;
	}
	//spin (counterclockwise?)
	else{
		motor[fr] = 100*speed;
		motor[fl] = -100*speed;
		motor[bl] = -100*speed ;
		motor[br] = 100*speed;
	}
}

void stopAll(){
	motor[fr] = 0;
	motor[fl] = 0;
	motor[bl] = 0;
	motor[br] = 0;
}

//x and y work like joystick values, -128 to 128
//Uses timer T1 for driving
void drive(int x, int y, float speed, int time){
	x = x / 128.0 * 100 * speed;
	y = y / 128.0 * 100 * speed;

	clearTimer(T1);

	motor[bl] = (-x + y);
	motor[br] = (x + y);
	motor[fr] = (-x + y);
	motor[fl] = (x + y);
	
	while(time1[T1] < time){
		
	}
	stopAll();
}

task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

	int x, y;

	while (true)
	{
	}
}
