#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorNone)
#pragma config(Sensor, S3,     light,          sensorNone)
#pragma config(Sensor, S4,     sonar,          sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     fl,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     bl,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     br,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     fr,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     shooterA,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     shooterB,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    holdright,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    holdleft,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "ButtonsDefs.h"
bool isholding = false;

void	 initializeRobot()
{
	bFloatDuringInactiveMotorPWM = false;

	return;
}


task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase
	servo[holdleft] = 0;
servo[holdright] = 255;
	int x, y;
	float speed = 0.75;

	while (true)
	{
		getJoystickSettings(joystick);



		if(joystick.joy1_Buttons == button_right_trigger){

			motor[fr] = -100*speed;
			motor[fl] = 100*speed;
			motor[bl] = 100*speed ;
			motor[br] = -100*speed;
		}

		else if(joystick.joy1_Buttons == button_left_trigger){

			motor[fr] = 100*speed;
			motor[fl] = -100*speed;
			motor[bl] = -100*speed ;
			motor[br] = 100*speed;
		}
		else{
			x = joystick.joy1_x1 / 128.0 * 100 * speed;
			y = joystick.joy1_y1 / 128.0 * 100 * speed;

		  motor[bl] = (-x + y);
			motor[br] = (x + y);
			motor[fr] = (-x + y);
			motor[fl] = (x + y);
		}

		if(joystick.joy1_TopHat == pov_west){
			servo[holdleft] = 255;
servo[holdright] = 0;

	}

	if(joystick.joy1_TopHat == pov_east){

servo[holdleft] = 0;
servo[holdright] = 255;

}

if(joystick.joy1_TopHat == pov_north){

motor[shooterA] = -100;
motor[shooterB] = -100;

}
else if(joystick.joy1_TopHat == pov_south){

motor[shooterA] = 100;
motor[shooterB] = 100;

}
else{
motor[shooterA] = 0;
motor[shooterB] = 0;

}
if(joystick.joy1_TopHat == pov_east){

servo[holdleft] = 0;
servo[holdright] = 255;

}
	if(joystick.joy1_Buttons == button_x){
if(isholding == true){
	servo[holdleft] = 0;
servo[holdright] = 255;
isholding = false;
}
else{
servo[holdleft] = 255;
servo[holdright] = 0;
isholding = true;
}


}


		if(joystick.joy1_Buttons == button_left_button){
			speed = 0.45;
		}
		else if(joystick.joy1_Buttons == button_right_button){
			speed = 1.0;
		}
		else{
			speed = 0.75;
		}



	}
}
