#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorG,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //Joystick is included in this program


task main()
{
	int threshold = 15; //to avoid unnecessary movement
	int negthreshold = -15;
	int motorDVal = 0; //Setting all motors and servos to zero
	int motorEVal = 0;
	int motorFVal = 0;
	int motorGVal = 0;
	int motorHVal = 0;
	int motorIVal = 0;
	int servo1Val = 127;
	int servo2Val = 127;
	int servo3Val = 127;
	int servo4Val = 63;
	eraseDisplay(); //Clear the display


	while(true) //infinite loop
	{
		getJoystickSettings(joystick);//retrieves data from the joystick

		string displayBString;  // Create a string to display the what joystick values are on the Brick

		motorDVal = 0;		// Set all Motor Values to zero
		motorEVal = 0;
		motorFVal = 0;
		motorGVal = 0;
		motorHVal = 0;
		motorIVal = 0;
		servo1Val = 127;
		servo2Val = 127;



		//Driving
		if(abs(joystick.joy1_y1) > threshold)
		{
			motorDVal = joystick.joy1_y1/2.5; //Go Straight When Left Stick is Pressed on Joystick 1
			motorEVal = joystick.joy1_y1/2.5;
			motorFVal = joystick.joy1_y1/2.5;
			motorGVal = joystick.joy1_y1/2.5;
		}
		if(abs(joystick.joy1_x2) > threshold)
		{
			motorDVal += joystick.joy1_x2/2.6;	//Turn when Left Stick is Pressed on Joystick 1
			motorFVal -= joystick.joy1_x2/2.6;
			motorEVal -= joystick.joy1_x2/2.6;
			motorGVal += joystick.joy1_x2/2.6;
		}



		//SLow sideways/Forwards driving With Top Hat
		if(joystick.joy1_TopHat == 0)		//Go Straight When the Top is Pressed
		{
			motorDVal = 15;
			motorEVal = 15;
			motorFVal = 15;
			motorGVal = 15;
		}
		else if(joystick.joy1_TopHat == 4)  //Go Backwards when the bottom is Pressed
		{
			motorDVal = -15;
			motorEVal = -15;
			motorFVal = -15;
			motorGVal = -15;
		}
		else if(joystick.joy1_TopHat == 6) //Go Sideways Right
		{
			motorDVal = -25;
			motorEVal = -25;
			motorFVal = 25;
			motorGVal = 25;
		}
		else if(joystick.joy1_TopHat == 2) //Go Sideways Left
		{
			motorDVal = 25;
			motorEVal = 25;
			motorFVal = -25;
			motorGVal = -25;
		}

		//Fast Sideways
		if(joystick.joy1_Buttons == 64) //Left Trigger
		{
			motorDVal = 75;
			motorEVal = 75;
			motorFVal = -75;
			motorGVal = -75;
		}

		else if(joystick.joy1_Buttons == 128) //Right Trigger
		{
			motorDVal = -75;
			motorEVal = -75;
			motorFVal = 75;
			motorGVal = 75;
		}

		//Diagonal
		if(joystick.joy1_Buttons == 16) //Left Button
		{
			motorDVal = 75;
			motorEVal = 75;
		}

		if(joystick.joy1_Buttons == 32) //Right Button
		{
			motorFVal = 75;
			motorGVal = 75;
		}


		//Collecting Blocks
		if(joystick.joy2_Buttons == 64) //Left Trigger
		{
			servo1Val = 0;
			servo2Val = 255;
		}

		if(joystick.joy2_Buttons == 128) //Right Trigger
		{
			servo1Val = 255;
			servo2Val = 0;
		}

		//Raising/Lowering BAM
		if(abs(joystick.joy2_y1) > threshold)
		{		if (joystick.joy2_y1> 0 )
			{
				motorHVal = 100;
			}
			else
			{
				motorHVal = -100;
			}
		}
		//Rotating BAM
		if(abs(joystick.joy2_y2) > threshold)
		{		if (joystick.joy2_y2> 0 )
			{
				motorIVal = 70;
			}
			else
			{
				motorIVal = -40;
			}
		}


		//Holding BAM still
		if(joystick.joy2_Buttons == 1)
		{
			motorIVal = 20;
		}


		//Releasing Blocks
		if(joystick.joy2_Buttons == 16)
		{
			servo4Val = 255;
		}
		if(joystick.joy2_Buttons == 32)
		{
			servo4Val = 63;
		}

		//Grab Blocks
		if(joystick.joy2_Buttons == 8)
		{
			motor[motorH] = -100;
			wait1Msec(600);
			motor[motorH] = 100;
			wait1Msec(700);
			motor[motorH] = 0;
		}

		//Releasing Lift
		if (joystick.joy2_Buttons == 2)
		{
			servo3Val = 127;
		}

		//Debugging
		{
			displayBString = joystick.joy2_Buttons;
			nxtDisplayTextLine(4, displayBString );
		}


		motor[motorD] = motorDVal; //Motor D is Right Front Wheel
		motor[motorE] = motorEVal; //Motor E is Left Front Wheel
		motor[motorF] = motorFVal; //Motor F is Right Back Wheel
		motor[motorG] = motorGVal; //Motor G is Left Back Wheel
		motor[motorH] = motorHVal; //Motor H is Raising/Lowering BAM
		motor[motorI] = motorIVal; //Motor I is Rotating BAM
		servo[servo1] = servo1Val; //Servo 1 is Collecting Blocks
		servo[servo2] = servo2Val; //Servo 2 is Collecting Blocks
		servo[servo3] = servo3Val; //Servo 3 is Releasing Lift
		servo[servo4] = servo4Val; //Servo 4 is Plunger
	}
}
